GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs?search=the

###
GET http://localhost:3001/api/blogs/7

###
PUT http://localhost:3001/api/blogs/15 HTTP/1.1
Content-Type: application/json

{
    "likes": 66
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtlbm9iaSIsImlkIjoyLCJpYXQiOjE2Nzg1NTIxNzd9.j-mrfq58Q-hBRoRfAC9CudYp6TjnIu22g4-cIDmj-Vs

{
    "author": "Anakin Skywalker",
    "url": "www.skywalker.com",
    "title": "I don't like sand"
}

###
DELETE http://localhost:3001/api/blogs/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtlbm9iaSIsImlkIjoyLCJpYXQiOjE2Nzg1NTIxNzd9.j-mrfq58Q-hBRoRfAC9CudYp6TjnIu22g4-cIDmj-Vs
