POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "obi-wan@kenobi.com",
    "password": "secret"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "anakin@skywalker.com",
    "password": "secret"
}
